# ==========================================================
# Development Environment (Kind)
# ==========================================================

global:
  namespace: beer-shop

  imagePullPolicy: Always

  storageClass: standard

  environment: 
    name: development
    type: development

# ==========================================================
# Infrastructure
# ==========================================================

consul:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

jaeger:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

kafka:
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

mongodb:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

mysql:
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi

redis:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi

# ==========================================================
# Backend Services
# ==========================================================

catalog:
  image:
    tag: "sha-069bcc1"
  replicaCount: 3
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

user:
  image:
    tag: "sha-069bcc1"
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

payment:
  image:
    tag: "sha-069bcc1"
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

order:
  image:
    tag: "sha-069bcc1"
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

shipping:
  image:
    tag: "sha-069bcc1"
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

courier:
  image:
    tag: "sha-069bcc1"
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

cart:
  image:
    tag: "sha-069bcc1"
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

shop-interface:
  image:
    tag: "sha-069bcc1"
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

shop-admin:
  image:
    tag: "sha-069bcc1"
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

# ==========================================================
# Frontend
# ==========================================================

web-shop:
  image:
    tag: "sha-069bcc1"
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

web-admin:
  image:
    tag: "sha-069bcc1"
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi