apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "shop-admin.fullname" . }}
  labels:
    {{- include "shop-admin.labels" . | nindent 4 }}

data:

  registry.yaml: |
{{ .Values.configs.registry | indent 4 }}