apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger.fullname" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "jaeger.selectorLabels" . | nindent 4 }}
  ports:
    - name: ui
      port: {{ .Values.service.ports.port.ui }}
      targetPort: {{ .Values.service.ports.port.ui }}
      protocol: TCP
    - name: collector
      port: {{ .Values.service.ports.port.collector }}
      targetPort: {{ .Values.service.ports.port.collector }}
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.ports.port.grpc }}
      targetPort: {{ .Values.service.ports.port.grpc }}
      protocol: TCP
    - name: otlp-grpc   # FIXED: Changed Grpc to grpc (lowercase)
      port: {{ .Values.service.ports.port.otlpgrpc }}
      targetPort: {{ .Values.service.ports.port.otlpgrpc }}
      protocol: TCP
    - name: otlp-http   # FIXED: Changed Http to http (lowercase)
      port: {{ .Values.service.ports.port.otlphttp }}
      targetPort: {{ .Values.service.ports.port.otlphttp }}
      protocol: TCP
