apiVersion: v1
kind: Service
metadata:
  name: {{ include "consul.fullname" . }}
  labels:
    {{- include "consul.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "consul.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}

    - name: server
      port: {{ .Values.service.ports.server }}
      targetPort: {{ .Values.service.ports.server }}

    - name: serf-lan
      port: {{ .Values.service.ports.serflan }}
      targetPort: {{ .Values.service.ports.serflan }}

    - name: serf-wan
      port: {{ .Values.service.ports.serfwan }}
      targetPort: {{ .Values.service.ports.serfwan }}

    - name: dns
      port: {{ .Values.service.ports.dns }}
      targetPort: {{ .Values.service.ports.dns }}