{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: {{ include "shop-interface.fullname" . }}
  labels:
    {{- include "shop-interface.labels" . | nindent 4 }}

spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}

  selector:
    matchLabels:
      {{- include "shop-interface.selectorLabels" . | nindent 6 }}
{{- end }}