apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "payment.fullname" . }}
  labels:
    {{- include "payment.labels" . | nindent 4 }}

data:

  registry.yaml: |
{{ .Values.configs.registry | indent 4 }}
    